# Generated by Django 5.2 on 2026-02-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_created_at_post_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
